### ISSUE TITLE
Some categories won't load

### ISSUE THREAD

**Issue by EduardHClevett** [carlssonemil/vanguard#7]
As the title says, some categories won't load, and consequently cause the 'All' category to fail loading too.

As far as I'm aware, the problematic ones are:

- All
- Launchers
- Melee

**Comment by carlssonemil** [comment]
Hm.. That's odd. I have confirmed that there's an issue in Firefox, but can't reproduce in my local development environment. I'll look at it during the day and see if I can find a solution! Thanks for reporting it!

**Comment by carlssonemil** [comment]
I think something is wrong with the value that is stored in your browsers [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage), since resetting the progress completely fixed the issue for me. I however added a ternary before returning the tooltip to check if the camouflage (which was missing) exists before trying to access it. See commit [11d5e85](https://github.com/carlssonemil/vanguard/commit/11d5e851f26ef1c986e2437a922df9d045a428cf).

@DisortingLines can you confirm that it is now fixed for you? I can't check since I reset my progress 😄 

If it doesn't work you can reset your progress by going into [Settings](https://vanguard.emca.app/settings) and then **Reset all progress**. If you're on PC you can export your current progress to a file and then import it after resetting. I hope this won't be too much of an inconvenience 😞

**Comment by EduardHClevett** [comment]
I can confirm the issue is fixed! Thanks for such a quick response! Love your charts, they saved my sanity throughout Damascus lmao
